name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: chmod +x ./gradlew
      - run: ./gradlew shadowJar
